import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <h1 className="text-center text-3xl m-3"> Dynamic cSV Display</h1>
        {children}
      </body>
    </html>
  );
}
